include:
  - local: '/.gitlab/cicd-template.yaml'

stages:
  - build
  - tests

2-1-10:
  image: "ruby:2.1.10"
  stage: build
  allow_failure: true
  extends: .install-template 
  script:
    - bundle install --jobs=3 --retry=3
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-1-10"
    paths:
      - ./*

2-2-10:
  image: "ruby:2.2.10"
  stage: build
  allow_failure: true
  extends: .install-template 
  script:
    - bundle install --jobs=3 --retry=3
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-2-10"
    paths:

2-4-5:
  image: "ruby:2.4.5"
  stage: build
  allow_failure: true
  extends: .install-template 
  script:
    - bundle install --jobs=3 --retry=3
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-4-5"
    paths:

2-5-5:
  image: "ruby:2.5.5"
  stage: build
  allow_failure: true
  extends: .install-template 
  script:
    - bundle install --jobs=3 --retry=3
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-5-5"
    paths:

2-6-3:
  image: "ruby:2.6.3"
  stage: build
  allow_failure: true
  extends: .install-template 
  script:
    - bundle install --jobs=3 --retry=3
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-6-3"
    paths:

rubyhead:
  image: "ruby:latest"
  stage: build
  allow_failure: true
  extends: .install-template 
  script:
    - bundle install --jobs=3 --retry=3
  cache:
    key: "$CI_COMMIT_REF_SLUG latest"
    paths:
      - ./*

2-1-10-test:
  image: "ruby:2.1.10"
  stage: tests
  allow_failure: true
  extends: .test-template
  script:
    - bundle exec rake test
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-1-10"
    paths:
      - ./*

2-2-10-test:
  image: "ruby:2.2.10"
  stage: tests
  allow_failure: true
  extends: .test-template
  script:
    - bundle exec rake test
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-2-10"
    paths:
      - ./*

2-4-5-test:
  image: "ruby:2.4.5"
  stage: tests
  allow_failure: true
  extends: .test-template
  script:
    - bundle exec rake test
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-4-5"
    paths:
      - ./*

2-5-5-test:
  image: "ruby:2.5.5"
  stage: tests
  allow_failure: true
  extends: .test-template
  script:
    - bundle exec rake test
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-5-5"
    paths:
      - ./*

2-6-3-test:
  image: "ruby:2.6.3"
  stage: tests
  allow_failure: true
  extends: .test-template
  script:
    - bundle exec rake test
  cache:
    key: "$CI_COMMIT_REF_SLUG 2-6-3"
    paths:
      - ./*

rubyhead-test:
  image: "ruby:latest"
  stage: tests
  allow_failure: true
  extends: .test-template
  script:
    - bundle exec rake test
  cache:
    key: "$CI_COMMIT_REF_SLUG latest"
    paths:
      - ./*
    
