version: '{build}'

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - "%devkit%\\devkitvars.bat"
  - ruby --version
  - gem --version
  - bundle install
build: off
test_script:
  - bundle exec rake test TESTOPTS=-v

branches:
  only:
    - master
    - v0.10
    - v0.12
    - v0.14

environment:
  matrix:
    - ruby_version: "22-x64"
      devkit: C:\Ruby21-x64\DevKit
    - ruby_version: "22"
      devkit: C:\Ruby21\DevKit
    - ruby_version: "21-x64"
      devkit: C:\Ruby21-x64\DevKit
    - ruby_version: "21"
      devkit: C:\Ruby21\DevKit
matrix:
  allow_failures:
    - ruby_version: "21"
